/*
  This file was auto-generated by Jinno.
*/
  
// "Primary" story - auto generated by Jinno.
export const Primary = {
  // 👇 You can add your component props to here
  args: {

  },
};

// 👇 You can add more story types if you like for your component
export const Secondary = {
  args: {
  },
};

// 👇 This tells Jinno which story to render.
export const selectedScenario = Primary;
  